version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "zoheb391"
      - "acdibble"
    commit-message:
      prefix: "chore"
      include: "scope"
